### Instalación de librerías

In [1]:
# !pip install eccd_datasets
# !pip install matplotlib
# !pip install seaborn

## Procesamiento de data

### Importar Librerias

In [2]:
from eccd_datasets import load_lingerie
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

datasets = load_lingerie() # use all the datasets together

In [3]:
type(datasets)

dict

### Imprimir los datos por cada vendedor

In [4]:
dataset_list = []
for i in datasets:
    data_i = datasets[i]
    dataset_list.append(data_i)
    print(i.upper())
    print(data_i.shape)
    display(data_i.head(1))
    print("----------------------------------------")
DATA = pd.concat(dataset_list)

AE_COM
(28328, 14)

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
0,Aerie Everyday Loves Lace Cheeky,12.50 USD,12.50 USD,https://www.ae.com/aerie-everyday-loves-lace-c...,AERIE,Cheekies,Ae US,Introducing Everyday Loves™: Made with love. E...,5.0,8.0,"[""Soft lace with the right amount of stretch"",...","[""XS"", ""S"", ""M"", ""L"", ""XL"", ""XXL""]","[""XS"", ""S"", ""M"", ""L"", ""XL"", ""XXL""]",Rugged Green

----------------------------------------
AMAZON_COM
(31612, 14)

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
0,Calvin Klein Women's Sheer Marquisette Demi Un...,$36.00,$32.40,https://www.amazon.com/-/dp/B01NAVD98J?th=1&psc=1,Calvin-Klein,Bras,Amazon US,"An unlined demi cup bra featuring sheer, sexy ...",4.5,47,"[ 72% Nylon, 28% Elastane , Imported , hook an...","30B , 30C , 30D , 30DD , 32A , 32B , 32C , 32D...","30B , 30C , 30D , 30DD , 32B , 32C , 32D , 32D...",Bare

----------------------------------------
BTEMPTD_COM
(3518, 14)

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
0,b.tempt'd Ciao Bella Bralette,$30.00,$30.00,http://btemptd.wacoal-america.com/b-tempt-d-ci...,WACOAL,COLLECTIONS,Btemptd US,Say “buongiorno!” to this ladylike piece that ...,NaN,NaN,[Wire free bralette • Cut and sew corded lace ...,"XS,S,M,L,XL","l,m,s,xl,xs",Bridal White

----------------------------------------
CALVINKLEIN_COM
(4747, 14)

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
0,logo cotton stretch thong,$13.00,$13.00,http://www.calvinklein.us/en/womens-clothing/w...,Calvin Klein,3 FOR 33 PANTY ESSENTIALS,Calvin Klein US,soft cotton stretch fabric and a metallic logo...,NaN,NaN,"[""cotton stretch thong panty"",""metallic elasti...","s,m,l","s,m,l",BLACK

----------------------------------------
HANKYPANKY_COM
(35005, 14)

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
0,Silky 20” A-line Half Slip with Lace,$68,$68,http://www.hankypanky.com/collections/silky-20...,HankyPanky,Collections,Hankypanky US,Hanky Panky Silky is the ideal fabric for unde...,NaN,NaN,"[""Just above-the-knee-length half-slip with el...","[""Select"", ""S"", ""M"", ""L"", ""XL""]","[""Select"", ""S"", ""M"", ""L"", ""XL""]",Black

----------------------------------------
MACYS_COM
(40897, 14)

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
0,ID String Bikini QF1754,$20.00,$20.00,http://www1.macys.com/shop/product/calvin-klei...,Calvin Klein,Women - Lingerie & Shapewear - Designer Lingerie,Macys US,The perfect amount of coverage in a subtle sil...,NaN,NaN,"[""Thin elastic waistband "", ""Repeating logo at...","[""XS"", ""S"", ""M"", ""L"", ""XL""]","[""XS"", ""S"", ""M"", ""L"", ""XL""]",Black

----------------------------------------
SHOP_NORDSTROM_COM
(12568, 14)

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
0,'B Fitting' High Cut Briefs,$15.00,$15.00,http://shop.nordstrom.com/s/wacoal-b-fitting-h...,WACOAL,Women's Panties,Nordstrom US,"Lighter-than-air, full-cut Supima® cotton brie...",4.2,65.0,"[""79% Supima® cotton, 21% spandex."", ""Hand was...",[nil],[nil],Black

----------------------------------------
US_TOPSHOP_COM
(3082, 14)

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
0,MATERNITY Criss Cross Knickers,$20.00,$20.00,http://www.topshop.com/en/tsus/product/clothin...,US TOPSHOP,Lingerie,Topshop US,These feminine black knickers for maternity fe...,NaN,NaN,NaN,"4,6,8,10,12","4,6,8,10,12",BLACK

----------------------------------------
VICTORIASSECRET_COM
(453386, 14)

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
0,Very Sexy Strappy Lace Thong Panty,$14.50,$14.50,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,peach melba

----------------------------------------

In [5]:
DATA.info()

<class 'pandas.core.frame.DataFrame'>
Index: 613143 entries, 0 to 453385
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   product_name      613143 non-null  object
 1   mrp               613143 non-null  object
 2   price             613143 non-null  object
 3   pdp_url           613143 non-null  object
 4   brand_name        613143 non-null  object
 5   product_category  613143 non-null  object
 6   retailer          613143 non-null  object
 7   description       613143 non-null  object
 8   rating            233556 non-null  float64
 9   review_count      222030 non-null  float64
 10  style_attributes  156675 non-null  object
 11  total_sizes       613143 non-null  object
 12  available_size    613143 non-null  object
 13  color             612466 non-null  object
dtypes: float64(2), object(12)
memory usage: 70.2+ MB

### Procesando columna `price`

In [6]:
DATA['price'] = DATA['price'].str.replace("USD","")
DATA['price'] = DATA['price'].str.replace("$","")
DATA['price'] = pd.to_numeric(DATA['price'],errors='coerce')

### Valore nulos por columna

In [7]:
DF_NULOS = pd.DataFrame(DATA.isna().sum(),columns=["NULOS"])
DF_NULOS['%'] = (DF_NULOS['NULOS']/613143)*100
DF_NULOS

                   NULOS          %
product_name           0   0.000000
mrp                    0   0.000000
price               3775   0.615680
pdp_url                0   0.000000
brand_name             0   0.000000
product_category       0   0.000000
retailer               0   0.000000
description            0   0.000000
rating            379587  61.908397
review_count      391113  63.788219
style_attributes  456468  74.447233
total_sizes            0   0.000000
available_size         0   0.000000
color                677   0.110415

In [8]:
DATA = DATA.drop(columns=['rating','review_count','style_attributes'])
DATA = DATA.dropna()

### Cantidad de valores por cada columna categorica

In [9]:
cat = list(DATA.select_dtypes(include=["object"]).columns)
num = list(DATA.select_dtypes(include=["number"]).columns)

In [10]:
DATA = DATA.reset_index(drop=True)
print(DATA.shape)
for i in cat:
    print(f"---------{i}---------")
    print(DATA[i].nunique())
    valores = pd.DataFrame(DATA[i].value_counts()).rename(columns={'count':'Cantidad'})
    valores['%'] =  (valores['Cantidad']/613143)*100
    valores['Acumulado'] = valores['%'].cumsum()
    display(valores)

(609368, 11)
---------product_name---------
2523

                                                 Cantidad         %  Acumulado
product_name
Body by Victoria Perfect Coverage Bra               17922  2.922972   2.922972
Victoria Sport Incredible by Victoria Sport Bra     12274  2.001817   4.924789
Dream Angels Push-Up Bra                            11878  1.937232   6.862021
Very Sexy Push-Up Bra                               10985  1.791589   8.653609
Body by Victoria Demi Bra                           10881  1.774627  10.428236
...                                                   ...       ...        ...
Endless Thong                                           1  0.000163  99.383667
Regular Rise Lace Thong                                 1  0.000163  99.383831
hashtag triangle bralette                               1  0.000163  99.383994
Full Figure Cooling Touch Underwire Bra 76355           1  0.000163  99.384157
'BARE - Eve' Natural Rise Thong                         1  0.000163  99.384320

[2523 rows x 3 columns]

---------mrp---------
756

         Cantidad         %  Acumulado
mrp
$10.50      48627  7.930776   7.930776
$36.50      45968  7.497109  15.427886
$34.50      35027  5.712697  21.140582
$34.95      26375  4.301607  25.442189
$54.50      23159  3.777096  29.219285
...           ...       ...        ...
$42.31          1  0.000163  99.383667
$40.30          1  0.000163  99.383831
$29.48          1  0.000163  99.383994
$34.72          1  0.000163  99.384157
$69.95          1  0.000163  99.384320

[756 rows x 3 columns]

---------pdp_url---------
11739

,Cantidad,%,Acumulado
pdp_url,,,
https://www.victoriassecret.com/bras/shop-all-bras/perfect-coverage-bra-body-by-victoria?ProductID=332957&CatalogueType=OLS,4531,0.738979,0.738979
https://www.victoriassecret.com/victorias-secret-sport/shop-all/knockout-by-victoria-sport-front-close-sport-bra-victoria-sport?ProductID=328521&CatalogueType=OLS,4027,0.656780,1.395759
https://www.victoriassecret.com/victorias-secret-sport/shop-all/incredible-by-victoria-sport-bra-victoria-sport?ProductID=336501&CatalogueType=OLS,3908,0.637372,2.033131
https://www.victoriassecret.com/bras/shop-all-bras/push-up-bra-very-sexy?ProductID=331335&CatalogueType=OLS,3594,0.586160,2.619291
https://www.victoriassecret.com/bras/shop-all-bras/perfect-coverage-bra-body-by-victoria?ProductID=328797&CatalogueType=OLS,3552,0.579310,3.198601
...,...,...,...
https://www.ae.com/aerie-deals-happy-unlined-bandeau-bra-maroon-lagoon/aerie/s-prod/2792_2308_645?cm=sDE-cEUR&catId=cat8150047,1,0.000163,99.383667
https://www.ae.com/bras-aerie-triangle-lace-trim-bralette-alpha-turquoise/aerie/s-prod/4447_2321_382?cm=sDE-cEUR&catId=cat7720427,1,0.000163,99.383831
https://www.amazon.com/-/dp/B00NW23XPC?th=1&psc=1,1,0.000163,99.383994
https://www.ae.com/aerie-sunnie-demi-coverage-lightly-lined-bra-ballet-pink/aerie/s-prod/2791_7824_133?cm=sDE-cEUR&catId=cat4130015,1,0.000163,99.384157
https://www.amazon.com/-/dp/B01MY4P0HX?th=1&psc=1,1,0.000163,99.384320

---------brand_name---------
32

,Cantidad,%,Acumulado
brand_name,,,
Victoria's Secret,342063,55.788454,55.788454
Victoria's Secret Pink,110817,18.073598,73.862052
HankyPanky,35005,5.709109,79.571160
Wacoal,28978,4.726141,84.297301
AERIE,28304,4.616215,88.913516
Calvin Klein,18880,3.079216,91.992733
Hanky Panky,8133,1.326444,93.319177
Calvin-Klein,7372,1.202330,94.521506
WACOAL,6580,1.073159,95.594666
b.tempt'd by Wacoal,5241,0.854776,96.449442
HANKY PANKY,4407,0.718756,97.168197
b-temptd,3490,0.569198,97.737396
CALVIN KLEIN,3142,0.512442,98.249837
Vanity Fair,2575,0.419967,98.669805
Calvin Klein Modern Cotton,1193,0.194571,98.864376
B.TEMPT'D BY WACOAL,912,0.148742,99.013118
NORDSTROM LINGERIE,870,0.141892,99.155010
Calvin Klein Performance,651,0.106174,99.261184
Hanky-Panky,582,0.094921,99.356105
b.tempt'd,69,0.011253,99.367358
Victorias-Secret,67,0.010927,99.378285
AEO,24,0.003914,99.382200
s,3,0.000489,99.382689
ref=w_bl_sl_l_b_ap_web_2603426011?ie=UTF8&node=2603426011&field-lbr_brands_browse-bin=Wacoal,2,0.000326,99.383015
Nintendo,1,0.000163,99.383178
Sexy-Hair,1,0.000163,99.383341
Creative-Motion,1,0.000163,99.383504
Lucky-Brand,1,0.000163,99.383667
ref=w_bl_sl_l_b_ap_web_2586451011?ie=UTF8&node=2586451011&field-lbr_brands_browse-bin=b.tempt%27d,1,0.000163,99.383831
Fila,1,0.000163,99.383994
ref=w_bl_sl_l_ap_ap_web_2586685011?ie=UTF8&node=2586685011&field-lbr_brands_browse-bin=Calvin+Klein,1,0.000163,99.384157
Compression-Comfort,1,0.000163,99.384320

---------product_category---------
525

                                  Cantidad         %  Acumulado
product_category
Demi Bra                             39811  6.492939   6.492939
Push-Up Bra                          36452  5.945106  12.438045
Bras                                 31103  5.072716  17.510760
Perfect Coverage Bra                 24762  4.038536  21.549296
Incredible by Victoria Sport Bra     19437  3.170060  24.719356
...                                    ...       ...        ...
Super SoftMuscle Tank                    5  0.000815  99.382363
Embroidered Triangle Bra                 4  0.000652  99.383015
Coconut Waters Travel Kit                3  0.000489  99.383504
Fresh & Clean Gym Kit                    3  0.000489  99.383994
Heart Lace Garter Belt                   2  0.000326  99.384320

[525 rows x 3 columns]

---------retailer---------
8

                    Cantidad          %  Acumulado
retailer
Victoriassecret US    452880  73.862052  73.862052
Macys US               40897   6.670059  80.532111
Hankypanky US          35005   5.709109  86.241219
Amazon US              31612   5.155730  91.396950
Ae US                  28328   4.620129  96.017079
Nordstrom US           12393   2.021225  98.038304
Calvin Klein US         4735   0.772251  98.810555
Btemptd US              3518   0.573765  99.384320

---------description---------
2925

,Cantidad,%,Acumulado
description,,,
"Our fullest coverage and our sexiest comfort meet in this supersoft bra with lighter Memory Fit lining that conforms to your curves and a smoothing U-shaped back and sides. Lift & Lining Lightly lined for shape Full coverage underwire cups Straps & Hooks Adjustable straps can convert to crossback and snap into place for a secure hold Back closure Double row of hook-and-eye closures; Sizes 34DDD, 36DD-36DDD, 38-40D-DDD & 40C have triple row of closures for a secure, comfortable fit 4 settings to ensure a perfect fit Details & Fabric U-shaped ballet back prevents band from riding up and offers more coverage Supersoft, double-lined sides for the smoothest shape Imported nylon/spandex",18529,3.021970,3.021970
"An everyday fave with soft, no-show cups and a super comfortable fit! Most push Super soft pad and smooth no-show cups Fully adjustable straps­–wear it classic or crossback Structured, underwire cups Hook-and-eye closure Imported nylon/spandex",15190,2.477399,5.499370
"Click, zip, go! Patented bra-within-a-bra technology offers maximum support: a front zip reveals structured cups that clip together for easy on, easy off…and no bounce. Details Maximum support Patented, bra-within-a-bra technology Click & zip within a bra; double layer front closure provides a secure fit Concealed wire for cushioned support Breathable padding with wicking liner to keep you extra dry Adjustable padded straps Performance & Fabric Perfect for running, boxing and cardio Super-soft elastic band for comfort & movement Body-Wick keeps you cool & dry Machine wash. Tumble dry Imported nylon/spandex",14887,2.427982,7.927351
"This dreamy demi is even more heavenly, with softer Memory Fit lining that conforms to your curves, a smoothing U-shaped back and stretchier lace sides for a flawless, ultra-comfy fit.Lift & Lining Lightly lined for shape Underwire cupsStraps & Hooks Adjustable straps can convert to crossback and snap into place for a secure hold Back closure Double row of hook and eye closures; sizes 36-40DD-DDD have triple row of hook and eye closures for a secure, comfortable fit 4 settings to ensure a perfect fitDetails & Fabric U-shaped ballet back prevents band from riding up Stretchy lace sides Imported nylon/spandex",11524,1.879496,9.806848
"Our #1 push-up is sexier than ever with plush, even softer padding for the lift and cleavage you love and a more natural feel, plus edges that disappear under clothes.Lift & Lining Push-up padding adds 1 cup size Underwire cupsStraps & Hooks Fully adjustable straps Back closure Double row of hook-and-eye closures 4 settings to ensure a perfect fit Can be worn classic or crossbackDetails & Fabric Supersmooth neckline disappears under clothes Cutouts between cups VS charm on side of cup Imported nylon/spandex",11307,1.844105,11.650953
...,...,...,...
Pair lovely lace and pretty bows for a perfectly feminine look with this bralette and bikini from Hanky Panky.,1,0.000163,99.383667
"Create a classic, enchanting look with a touch of chic modern style with this merry widow and thong duet from CK Black by Calvin Klein.",1,0.000163,99.383831
"Your new go-to for a full-figured look is the smooth, satiny Comfort X3 bra from Vanity Fair.",1,0.000163,99.383994
Smooth support that looks excellent under all of your favorite clothes. The Full Figure Cooling Touch Underwire Bra by Vanity Fair. Style #76355,1,0.000163,99.384157
"These silky-soft briefs ensure a smooth, comfortable fit with no visible lines thanks to a high-waist, seamless construction and full-coverage cut. Softer and stretchier than the Shimera Seamless Full Briefs it’s replacing, this new and improved Nordstrom style offers the same great coverage and fit.",1,0.000163,99.384320

---------total_sizes---------
932

,Cantidad,%,Acumulado
total_sizes,,,
"[""XS"", ""S"", ""M"", ""L"", ""XL""]",100224,16.345942,16.345942
"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""32DDD"", ""34A"", ""34B"", ""34C"", ""34D"", ""34DD"", ""34DDD"", ""36A"", ""36B"", ""36C"", ""36D"", ""36DD"", ""36DDD"", ""38A"", ""38B"", ""38C"", ""38D"", ""38DD"", ""38DDD"", ""40A"", ""40B"", ""40C"", ""40D"", ""40DD"", ""40DDD""]",53884,8.788162,25.134104
"[""XS"", ""S"", ""M"", ""L""]",53528,8.730100,33.864205
"[""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""30DDD"", ""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""32DDD"", ""34A"", ""34B"", ""34C"", ""34D"", ""34DD"", ""34DDD"", ""36A"", ""36B"", ""36C"", ""36D"", ""36DD"", ""36DDD"", ""38A"", ""38B"", ""38C"", ""38D"", ""38DD"", ""38DDD"", ""40A"", ""40B"", ""40C"", ""40D"", ""40DD"", ""40DDD""]",51687,8.429844,42.294049
"[""30AA"", ""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""32AA"", ""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34AA"", ""34A"", ""34B"", ""34C"", ""34D"", ""34DD"", ""36AA"", ""36A"", ""36B"", ""36C"", ""36D"", ""36DD""]",48941,7.981988,50.276037
...,...,...,...
"[""XXS"", ""XS"", ""S"", ""L"", ""XL""]",1,0.000163,99.383667
"[""32D"", ""34C"", ""34D"", ""34DD"", ""36C"", ""36D"", ""36DD"", ""36DDD"", ""38C"", ""38D"", ""38DD""]",1,0.000163,99.383831
"[""32C"", ""32D"", ""32DD"", ""34B"", ""34C"", ""36B"", ""36C"", ""38B""]",1,0.000163,99.383994
"[""32D"", ""34C"", ""34D"", ""34DD"", ""36C"", ""36D"", ""36DD"", ""36DDD"", ""38C"", ""38D""]",1,0.000163,99.384157
"[""Select"", ""1X""]",1,0.000163,99.384320

---------available_size---------
7354

,Cantidad,%,Acumulado
available_size,,,
S,30436,4.963932,4.963932
XS,30239,4.931802,9.895734
M,29858,4.869663,14.765397
L,29332,4.783876,19.549273
XL,16914,2.758573,22.307847
...,...,...,...
"32C , 32D , 32DD , 32G , 34C , 34D , 34DD , 34DDD , 36C , 36D , 36DD , 36DDD , 36G , 38C , 38D , 38DD , 38DDD , 38G , 40C , 40D , 40DD , 40DDD , 42D , 42DD",1,0.000163,99.383667
"32D , 32DDD , 32H , 34DD , 34G , 34H , 36D , 36DD , 36DDD , 36G , 36H , 38D , 38DD , 38DDD , 38G , 38H , 40D , 40DD , 40DDD , 42DDD , 44D , 44DD , 44DDD",1,0.000163,99.383831
"32D , 32DD , 32DDD , 32G , 32H , 34D , 34DD , 34H , 36D , 36DDD , 36H , 38D , 38DD , 38DDD , 38G , 40DD , 40DDD , 40G , 40H , 42D , 42DD , 42DDD , 44D , 44DD , 44DDD",1,0.000163,99.383994
"32C , 32D , 32G , 32H , 34C , 34D , 34DD , 34DDD , 34G , 36C , 36D , 36DD , 36DDD , 36G , 36H , 38C , 38D , 38DD , 38DDD , 38G , 38H , 40C , 40D , 40DD , 40G , 40H , 42D",1,0.000163,99.384157
"32C , 32D , 32DD , 34B , 34C , 34D , 34DD , 36B , 36C , 36D , 38B , 38C , 38D , 38DD , 40B , 40C , 40D , 40DD",1,0.000163,99.384320

---------color---------
2506

                                     Cantidad         %  Acumulado
color
Black                                   36899  6.018009   6.018009
White                                   18069  2.946947   8.964956
black                                   13129  2.141262  11.106218
pure black                               7097  1.157479  12.263697
Ensign                                   6707  1.093872  13.357569
...                                       ...       ...        ...
Unique/Bitter/White                         1  0.000163  99.383667
BLUE PULSE                                  1  0.000163  99.383831
French Roast/Unique/Continuous Skin         1  0.000163  99.383994
One Size Fits Most                          1  0.000163  99.384157
Violet Tulle                                1  0.000163  99.384320

[2506 rows x 3 columns]

### Selección de columnas para el modelo

En base a hay muchas columnas de alta variabilidad, se eligen columnas que podría considerarse más apotantes al modelo

In [11]:
DATA_MODELO = DATA[['price','product_category','brand_name','color']] # Sin 'product_name'

In [12]:
DATA_MODELO.head(2)

   price product_category brand_name         color
0   12.5         Cheekies      AERIE  Rugged Green
1   12.5         Cheekies      AERIE  Natural Nude

**Columna: "brand_name"**

In [13]:
DATA_MODELO['brand_name'] = DATA_MODELO['brand_name'].str.upper()
DATA_MODELO['brand_name'] = DATA_MODELO['brand_name'].str.replace('-',' ')
DATA_MODELO['brand_name'] = DATA_MODELO['brand_name'].str.replace("'",'')
DATA_MODELO['brand_name'] = DATA_MODELO['brand_name'].str.replace(" ",'')
DATA_MODELO['brand_name'] = DATA_MODELO['brand_name'].str.replace(".",'')

def procesar_brand(row):
    if 'VICTORIASSECRET' in row:
        return "Victoria's Secret"
    elif 'HANKYPANKY' in row:
        return "Hanky-Panky"
    elif 'WACOAL' in row:
        return "Wacoal"
    elif 'CALVINKLEIN' in row:
        return "Calvin Klein" ############# Hasta aca la mayoria
    elif 'AERIE' in row:
        return "AERIE"
    elif 'BTEMPTD' in row:
        return "B. Tempt'd"
    elif 'VANITYFAIR' in row:
        return "Vanity Fair"
    elif 'NORDSTROMLINGERIE' in row:
        return "Nordstrom"
    else:
        return "Otro"

DATA_MODELO['brand_name'] = DATA_MODELO['brand_name'].apply(procesar_brand)

In [14]:
valores = pd.DataFrame(DATA_MODELO['brand_name'].value_counts()).rename(columns={'count':'Cantidad'})
valores['%'] =  (valores['Cantidad']/613143)*100
valores['Acumulado'] = valores['%'].cumsum()
# valores[valores['Acumulado']<=80]
valores

                   Cantidad          %  Acumulado
brand_name
Victoria's Secret    452947  73.872979  73.872979
Hanky-Panky           48127   7.849229  81.722208
Wacoal                41713   6.803144  88.525352
Calvin Klein          31238   5.094733  93.620085
AERIE                 28304   4.616215  98.236301
B. Tempt'd             3559   0.580452  98.816752
Vanity Fair            2575   0.419967  99.236720
Nordstrom               870   0.141892  99.378612
Otro                     35   0.005708  99.384320

**Columna: "product_category"**

In [15]:
DATA_MODELO_2 = DATA_MODELO.copy()
def categorias(d):
    if 'Bra' in d:
        return 'Bra'
    elif 'Panti' in d:
        return 'Panties'
    else:
        return d

DATA_MODELO_2['product_category_2'] = DATA_MODELO_2['product_category'].apply(categorias)

In [16]:
DATA_MODELO_2[DATA_MODELO_2['product_category_2']=='Bra']['price'].value_counts()

price
36.50    33376
34.50    24472
34.95    22244
19.99    21683
54.50    18521
         ...
38.75        1
86.00        1
50.01        1
59.81        1
42.48        1
Name: count, Length: 1337, dtype: int64

*Hay alta variabilidad en los **precios** de productos "Bra" por ello no es recomendable agrupar a las categorias que llevan el nombre "Bra" en una sola*

In [17]:
# marca = DATA_MODELO_.groupby('product_category').agg({'brand_name':'nunique','price':'nunique'})

In [18]:
valores = pd.DataFrame(DATA_MODELO['product_category'].value_counts()).rename(columns={'count':'Cantidad'})
valores['%'] =  (valores['Cantidad']/613143)*100
valores['Acumulado'] = valores['%'].cumsum()
porc = 70
print(valores[valores['Acumulado']<=porc].shape)
# valores[valores['Acumulado']<=porc].join(marca)
valores = valores[valores['Acumulado']<=porc]
valores

(50, 3)

,Cantidad,%,Acumulado
product_category,,,
Demi Bra,39811,6.492939,6.492939
Push-Up Bra,36452,5.945106,12.438045
Bras,31103,5.072716,17.510760
Perfect Coverage Bra,24762,4.038536,21.549296
Incredible by Victoria Sport Bra,19437,3.170060,24.719356
Women - Lingerie & Shapewear - Designer Lingerie,18893,3.081337,27.800692
Wear Everywhere Push-Up Bra,17438,2.844035,30.644727
Perfect Shape Bra,15557,2.537255,33.181982
Collections,15216,2.481640,35.663622
Knockout by Victoria Sport Front-Close Sport Bra,14887,2.427982,38.091603
Panties,11792,1.923206,40.014809
Women - Lingerie & Shapewear - Panties,10592,1.727493,41.742302
Thongs,9980,1.627679,43.369981
Wear Everywhere T-Shirt Bra,9812,1.600279,44.970260
Incredible by Victoria Sport Front-close Sport Bra,9715,1.584459,46.554719
Women - Lingerie & Shapewear - Bras,9300,1.516775,48.071494
Multi-Way Bra,7501,1.223369,49.294863
Wear Everywhere Lightly Lined Bra,7112,1.159925,50.454788
Lightweight by Victoria Sport Bra,6967,1.136277,51.591064
Add-2-Cups Push-Up Bra,6392,1.042497,52.633562
Wear Everywhere T-Back Push-Up Bra,5863,0.956221,53.589782
Unlined Demi Bra,5576,0.909413,54.499195
Easy Push-Up Bra,5480,0.893756,55.392951
Women's Panties,4772,0.778285,56.171236
Strappy Push-Up Bra,4510,0.735554,56.906790
Boybriefs,4402,0.717940,57.624730
Bras-and-tops,4213,0.687115,58.311846
Wireless Bra,4143,0.675699,58.987545
The Date Push-Up Bra,4117,0.671458,59.659003
Easy Plunge Bra,3976,0.648462,60.307465
Scoopneck Bralette,3709,0.604916,60.912381
Wear Everywhere Super Push,3694,0.602470,61.514851
Add-1½-Cups Push-Up Bra,3654,0.595946,62.110796
Skin-Tone Lingerie,3618,0.590074,62.700871
The Date Racerback Push-Up Bra,3322,0.541799,63.242669
Hiphugger Panty,3297,0.537721,63.780391
Lace T-Shirt Bra,3261,0.531850,64.312240
Front-close Bralette,3116,0.508201,64.820442
Strapless Balconet Bra,2765,0.450955,65.271397
Wear Everywhere Multi-Way Push-Up Bra,2761,0.450303,65.721700
The Wicked Unlined Uplift Bra,2758,0.449814,66.171513
Lightweight by Victoria Sport Strappy Sport Bra,2751,0.448672,66.620185
Palm Lace Strappy Push-Up,2717,0.443127,67.063311
Bralettes,2617,0.426817,67.490129
Lace Easy Push-Up Bra,2541,0.414422,67.904551
Everyday Loves Undies 7 for $27.50 USD,2420,0.394688,68.299239
Lace Plunge Unlined Demi Bra,2358,0.384576,68.683814
Lingerie,2260,0.368593,69.052407
Lightly Lined Triangle Bralette,2161,0.352446,69.404853
Bikini Panty,2134,0.348043,69.752896

*el 70% de los datos lo acupan 50 categorías por ello se van  a mantener estas y las demas se agruparan en una genérica*

In [19]:
def recategorizar(c):
    if c in valores.index.to_list():
        return c
    else:
        return "Otro"
    
DATA_MODELO['product_category'] = DATA_MODELO['product_category'].apply(recategorizar)

Columna: "color"

In [20]:
DATA_MODELO['color'] = DATA_MODELO['color'].str.lower()
DATA_MODELO['color'] = DATA_MODELO['color'].str.replace("-","")
DATA_MODELO['color'] = DATA_MODELO['color'].str.replace(" ","")
# DATA_MODELO['color'] = DATA_MODELO['color'].str.capitalize()

In [21]:
DATA_MODELO_3 = DATA_MODELO.copy()
def color(d):
    if 'black' in d:
        return 'Black'
    elif 'white' in d:
        return 'White'
    elif 'ensign' in d:
        return 'Ensign'
    else:
        return d

DATA_MODELO_3['color_2'] = DATA_MODELO_3['color'].apply(color)
DATA_MODELO_3[DATA_MODELO_3['color_2']=='Black']['price'].value_counts()

price
36.50    9386
10.50    6316
34.50    4992
19.99    4477
29.50    3996
         ...
46.56       1
40.82       1
38.08       1
14.62       1
18.77       1
Name: count, Length: 609, dtype: int64

*Hay alta variabilidad en los **precios** de productos "Black" por ello no es recomendable agrupar a los colore que llevan el nombre "black" en una sola*

In [22]:
valores = pd.DataFrame(DATA_MODELO['color'].value_counts()).rename(columns={'count':'Cantidad'})
valores['%'] =  (valores['Cantidad']/613143)*100
valores['Acumulado'] = valores['%'].cumsum()
valores = valores[valores['Acumulado']<=50]
print(valores.shape)
valores.head()

(96, 3)

              Cantidad         %  Acumulado
color
black            50933  8.306871   8.306871
white            21746  3.546644  11.853515
ensign            7788  1.270177  13.123692
pureblack         7097  1.157479  14.281171
coconutwhite      6259  1.020806  15.301977

In [23]:
def colores_resumen(c):
    if c in valores.index.to_list():
        return c
    else:
        return "Otro"
    
DATA_MODELO['color'] = DATA_MODELO['color'].apply(colores_resumen)

In [24]:
DATA_MODELO

        price product_category         brand_name         color
0        12.5             Otro              AERIE          Otro
1        12.5             Otro              AERIE   naturalnude
2        12.5             Otro              AERIE     trueblack
3        12.5             Otro              AERIE         white
4        12.5             Otro              AERIE          Otro
...       ...              ...                ...           ...
609363   48.0             Otro  Victoria's Secret  coconutwhite
609364   48.0             Otro  Victoria's Secret   mulledgrape
609365   48.0             Otro  Victoria's Secret     sheerpink
609366   48.0             Otro  Victoria's Secret  coconutwhite
609367   48.0             Otro  Victoria's Secret   mulledgrape

[609368 rows x 4 columns]

### Guardar la data procesada en Storage

In [ ]:
from google.cloud import storage 
storage_client = storage.Client()

csv_bytes = DATA_MODELO.to_csv(index=False)
bucket = storage_client.get_bucket('price_lingerie_predict_eu')
blob = bucket.blob('data/DATA_MODELO.csv')
blob.upload_from_string(csv_bytes, content_type='text/csv')
# DATA_MODELO.to_csv('DATA_MODELO.csv',index=False)